matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_AU
    mode: markdown
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.fenced_code:
  - pyspelling.filters.html:
      ignores:
      - pre
      - code
      - a
  sources:
    - '!venv/**/*.md|**/*.md'
  default_encoding: utf-8
