site_name: Scaffold Docs
site_url: https://scaffold.ragedriven.dev/
repo_url: https://github.com/RhysDeimel/scaffold
repo_name: RhysDeimel/scaffold

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search

extra:
  version:
    provider: mike


nav:
  - Scaffold Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
