name: Task  🛠️
description: A unit of work that needs doing
labels: ["triage", "task"]
## Type is only available with paid plans
# labels: ["triage"]
# type: task

body:
- type: textarea
  attributes:
    label: Description
    description: A short description of what needs to be done. A TLDR.

- type: textarea
  attributes:
    label: Implementation
    description: A clear and concise description of what you want to happen.

- type: textarea
  attributes:
    label: Context
    description: Add any other information, ticket/ issues links or screenshots about the request here.
