name: version check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout compare
        uses: actions/checkout@v2

      - name: Checkout base
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: 'base'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-


      - name: Install Packaging
        run: pip install packaging

      - name: debug
        run: |
          ls -alh
          ls -alh base